[package]
name = "gite"
version = "0.1.0"
authors = ["Teemu Erkkola <teemu.erkkola@iki.fi>"]
edition = "2018"

[dependencies]
hyper = "0.12"
git2 = "0.9"
structopt = "0.2.18"
log = "0.4.6"
simple_logger = "1.3.0"
