[package]
name = "gite"
version = "0.2.0"
authors = ["Teemu Erkkola <teemu.erkkola@iki.fi>"]
edition = "2018"

[dependencies]
hyper = "0.13"
git2 = "0.12"
structopt = "0.3.9"
log = "0.4.8"
simple_logger = "1.6.0"
tokio = { version = "0.2", features = ["full"] }
